package xyz.janboerman.scalaloader.util;

import xyz.janboerman.scalaloader.compat.Compat;
import xyz.janboerman.scalaloader.plugin.description.ScalaVersion;

import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.Map;
import java.util.Objects;

import static xyz.janboerman.scalaloader.compat.Compat.mapOf;
import static xyz.janboerman.scalaloader.compat.Compat.mapEntry;

/**
 * Utility class for getting SHA-1 hashes of Scala library artifacts from Maven Central.
 */
public final class ScalaHashes {

    /** Generated by {@linkplain #main(String[])}. */
    private static final Map<ScalaHash, String> SHA1_HASHES = mapOf(
            mapEntry(new ScalaHash("2.11.12", "scala-reflect-url"), "2bb23c13c527566d9828107ca4108be2a2c06f01"),
            mapEntry(new ScalaHash("2.11.12", "scala-library-url"), "bf5534e6fec3d665bd6419c952a929a8bdd4b591"),
            mapEntry(new ScalaHash("2.12.6", "scala-reflect-url"), "f2c1ebc398963457d3b62dddde4562decb32e39a"),
            mapEntry(new ScalaHash("2.12.6", "scala-library-url"), "6bd975dd5ca2a50b94413b708389b892ae423181"),
            mapEntry(new ScalaHash("2.12.7", "scala-reflect-url"), "c5a8eb12969e77db4c0dd785c104b59d226b8265"),
            mapEntry(new ScalaHash("2.12.7", "scala-library-url"), "18c09ad08ec783f5074f4a0d6308a78759000cb1"),
            mapEntry(new ScalaHash("2.12.8", "scala-reflect-url"), "682d33402cdae50258afa2c0860eb54688dab610"),
            mapEntry(new ScalaHash("2.12.8", "scala-library-url"), "36b234834d8f842cdde963c8591efae6cf413e3f"),
            mapEntry(new ScalaHash("2.12.9", "scala-reflect-url"), "9121d13a040727c986de85f27abd8e5b2d8ba502"),
            mapEntry(new ScalaHash("2.12.9", "scala-library-url"), "846dedb6587756b42575d19169d55495e76ba0d5"),
            mapEntry(new ScalaHash("2.12.10", "scala-reflect-url"), "14cb7beb516cd8e07716133668c427792122c926"),
            mapEntry(new ScalaHash("2.12.10", "scala-library-url"), "3509860bc2e5b3da001ed45aca94ffbe5694dbda"),
            mapEntry(new ScalaHash("2.12.11", "scala-reflect-url"), "7695010d1f4309a9c4b65be33528e382869ab3c4"),
            mapEntry(new ScalaHash("2.12.11", "scala-library-url"), "1a0634714a956c1aae9abefc83acaf6d4eabfa7d"),
            mapEntry(new ScalaHash("2.12.12", "scala-reflect-url"), "724278c9eb08825e176f3ed0ce49556886a2f7f7"),
            mapEntry(new ScalaHash("2.12.12", "scala-library-url"), "ea37f7d72b5b9332279a24f7856de4043b60bdc0"),
            mapEntry(new ScalaHash("2.12.13", "scala-reflect-url"), "9f044e6610b4f6a875fd8f055687d604040b424b"),
            mapEntry(new ScalaHash("2.12.13", "scala-library-url"), "c4a2c5f551238795136cb583feef73ae78651e07"),
            mapEntry(new ScalaHash("2.12.14", "scala-reflect-url"), "7116526cd205bb709241b29426ff98291f7facd0"),
            mapEntry(new ScalaHash("2.12.14", "scala-library-url"), "1c65e76e15684d378fa2deb4ebe536a68e10c9bf"),
            mapEntry(new ScalaHash("2.12.15", "scala-reflect-url"), "3eca572cf97238683a8a545dabb22b52781547c8"),
            mapEntry(new ScalaHash("2.12.15", "scala-library-url"), "0f2e89c89340282c9625ac57efb451056f31af57"),
            mapEntry(new ScalaHash("2.12.16", "scala-reflect-url"), "b5c65071a191d4a202b9d98615ece9a36a1e2fd7"),
            mapEntry(new ScalaHash("2.12.16", "scala-library-url"), "2b154d8ce179db26cbf3a3a36a996c0ea511a8e0"),
            mapEntry(new ScalaHash("2.12.17", "scala-reflect-url"), "c0fcfc7932ee0c92e6d00d1c7c47d5042391a987"),
            mapEntry(new ScalaHash("2.12.17", "scala-library-url"), "4a4dee1ebb59ed1dbce014223c7c42612e4cddde"),
            mapEntry(new ScalaHash("2.12.18", "scala-reflect-url"), "7e1a6985bfbe78bdc94f33613301ef385d4629b4"),
            mapEntry(new ScalaHash("2.12.18", "scala-library-url"), "fa825f984172f6801e3d8c476071b1823c0a925b"),
            mapEntry(new ScalaHash("2.12.19", "scala-reflect-url"), "76c5600f371936a8c8fed925cb76791e212d3715"),
            mapEntry(new ScalaHash("2.12.19", "scala-library-url"), "719d843f28afd3239726b7aab9c5c9171aae1d80"),
            mapEntry(new ScalaHash("2.12.20", "scala-reflect-url"), "f923933d1c168535e66ca825c18207a8db2b20a6"),
            mapEntry(new ScalaHash("2.12.20", "scala-library-url"), "562dc9629943eec010e27898c3be65ffa9210558"),
            mapEntry(new ScalaHash("2.13.0", "scala-reflect-url"), "2dbe07b0369dbf00a098b7925b2afca016f124b0"),
            mapEntry(new ScalaHash("2.13.0", "scala-library-url"), "e988ea597113786768900f1c260c694a2ae32a42"),
            mapEntry(new ScalaHash("2.13.1", "scala-reflect-url"), "c4123cd3d2a7502d16f443cd52fb23763bef8402"),
            mapEntry(new ScalaHash("2.13.1", "scala-library-url"), "1418c956704990564fb9dfac5960647ca54b5a91"),
            mapEntry(new ScalaHash("2.13.2", "scala-reflect-url"), "2a6dd4989a27aba0dd43bc297045cff633d70064"),
            mapEntry(new ScalaHash("2.13.2", "scala-library-url"), "280d2a51b3130cf869cb416404b2c0e44e433f3e"),
            mapEntry(new ScalaHash("2.13.3", "scala-reflect-url"), "0eb08a460df09947c423e5ce77b3d4af566085f1"),
            mapEntry(new ScalaHash("2.13.3", "scala-library-url"), "1431ec9962701faf77bbd5e1449ded674be6fe5b"),
            mapEntry(new ScalaHash("2.13.4", "scala-reflect-url"), "922b2d8f4c0754fa0b2ab9bfe670aa51a1d084cb"),
            mapEntry(new ScalaHash("2.13.4", "scala-library-url"), "b6781c71dfe4a3d5980a514eec8a513f693ead95"),
            mapEntry(new ScalaHash("2.13.5", "scala-reflect-url"), "08dee4d8c5374920f2db2f5f55d9dd6ecd4194cc"),
            mapEntry(new ScalaHash("2.13.5", "scala-library-url"), "d0df6e78b6ccb0102cb0395bfa8cb806e9e81b61"),
            mapEntry(new ScalaHash("2.13.6", "scala-reflect-url"), "bb523e56c63746a5752dece28fcd702c54fd3a11"),
            mapEntry(new ScalaHash("2.13.6", "scala-library-url"), "ed7a2f528c7389ea65746c22a01031613d98ab3d"),
            mapEntry(new ScalaHash("2.13.7", "scala-reflect-url"), "a069f7084f37d9678fa80dd0433efca1cf2b0dce"),
            mapEntry(new ScalaHash("2.13.7", "scala-library-url"), "92daa1ebe0ac486794379c49d0b70c89a0272012"),
            mapEntry(new ScalaHash("2.13.8", "scala-reflect-url"), "994b004d041b18724ec298a135c37e7817d369ec"),
            mapEntry(new ScalaHash("2.13.8", "scala-library-url"), "5a865f03a794b27e6491740c4c419a19e4511a3d"),
            mapEntry(new ScalaHash("2.13.9", "scala-reflect-url"), "10c5370efc4637a0a6e05df82c460dcdab09e446"),
            mapEntry(new ScalaHash("2.13.9", "scala-library-url"), "48bad4bee84f503be847be81ae96d32f6e78d658"),
            mapEntry(new ScalaHash("2.13.10", "scala-reflect-url"), "f19c2a5fc93a63398a5cfc56a14f0abf1d28d27c"),
            mapEntry(new ScalaHash("2.13.10", "scala-library-url"), "67c1afabaea9ba51321159e70a78515647e1b73d"),
            mapEntry(new ScalaHash("2.13.11", "scala-reflect-url"), "965b382f32d914716b0c6a8d05956a3600a7b35a"),
            mapEntry(new ScalaHash("2.13.11", "scala-library-url"), "4fcd82e1ce42d7b157914b86864e7b3591e1e0d2"),
            mapEntry(new ScalaHash("2.13.12", "scala-reflect-url"), "88be4dbc90fdd2d12c05b6a872a9add60524461d"),
            mapEntry(new ScalaHash("2.13.12", "scala-library-url"), "3c51da898af4ebfac356fcde11388afb2ae8ee82"),
            mapEntry(new ScalaHash("2.13.13", "scala-reflect-url"), "46866f0e2cf6168322dc11f0f721c2db78d52ac7"),
            mapEntry(new ScalaHash("2.13.13", "scala-library-url"), "3b1434403ddb147b8030f98f246153e4ce622c78"),
            mapEntry(new ScalaHash("2.13.14", "scala-reflect-url"), "8e275fefb2a01e178db2cdfebb2181062a790b82"),
            mapEntry(new ScalaHash("2.13.14", "scala-library-url"), "f8b4afe89abe48ca670f620c7da89b71f93e6546"),
            mapEntry(new ScalaHash("2.13.15", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("2.13.15", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.0.0", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.0.0", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.0.0", "scala3-library-url"), "9b07afcc82e941ce34049cb8b5dcccd444e780eb"),
            mapEntry(new ScalaHash("3.0.0", "tasty-core-url"), "5c0206b289596de98ad321ca30b8509a076ab1b0"),
            mapEntry(new ScalaHash("3.0.1", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.0.1", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.0.1", "scala3-library-url"), "2cfa10d6c8825f69972ee1d75deb12cbb0b1fa34"),
            mapEntry(new ScalaHash("3.0.1", "tasty-core-url"), "fd9b30b5e2bf65dcfd8f262c2d5201cc0d9c45a5"),
            mapEntry(new ScalaHash("3.0.2", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.0.2", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.0.2", "scala3-library-url"), "e7bdb8e4b336f3dea5f25e46270de5968d402a1b"),
            mapEntry(new ScalaHash("3.0.2", "tasty-core-url"), "41a664ae7e9a2c0b60fa265a483d24df0f3885e4"),
            mapEntry(new ScalaHash("3.1.0", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.1.0", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.1.0", "scala3-library-url"), "c04dbffc2e8eb159dcc31e9db3fb2618de13cf0d"),
            mapEntry(new ScalaHash("3.1.0", "tasty-core-url"), "b4bdeb64cef40d6e35cc39d758ff11796da8d91f"),
            mapEntry(new ScalaHash("3.1.1", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.1.1", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.1.1", "scala3-library-url"), "db9aefaffa12fd9fba2dfe84b7dc9c4ae676de0b"),
            mapEntry(new ScalaHash("3.1.1", "tasty-core-url"), "2419ccce181852c1d042af9a24866bb0daa95ebf"),
            mapEntry(new ScalaHash("3.1.2", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.1.2", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.1.2", "scala3-library-url"), "709b414a7924204b2dc0dd4a9740c2d3be3a5ef5"),
            mapEntry(new ScalaHash("3.1.2", "tasty-core-url"), "b62a515963283ec8949ad302a3a1d56f8990251b"),
            mapEntry(new ScalaHash("3.1.3", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.1.3", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.1.3", "scala3-library-url"), "bc6b3df836202e833292c6dd09aeaf0a8ced45fd"),
            mapEntry(new ScalaHash("3.1.3", "tasty-core-url"), "3073fc79f7991ab073929bf7edc2ab6ef3655965"),
            mapEntry(new ScalaHash("3.2.0", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.2.0", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.2.0", "scala3-library-url"), "d775805d7d73cd4d9d9c734cc04e4d923cd19065"),
            mapEntry(new ScalaHash("3.2.0", "tasty-core-url"), "19c7a001b3523a7392534bb339a83ef6bbbff090"),
            mapEntry(new ScalaHash("3.2.1", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.2.1", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.2.1", "scala3-library-url"), "ddc77e1f365f0a5202dda84eefede515feb93784"),
            mapEntry(new ScalaHash("3.2.1", "tasty-core-url"), "09de0f4eace4584394bf2bf941396962f5547e0b"),
            mapEntry(new ScalaHash("3.2.2", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.2.2", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.2.2", "scala3-library-url"), "66cd4d151f70d4545b358d25b5a8377e68a4ded5"),
            mapEntry(new ScalaHash("3.2.2", "tasty-core-url"), "808c8ce3f296c2d6cd5a7cdbeeff4e3af467913a"),
            mapEntry(new ScalaHash("3.3.0", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.3.0", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.3.0", "scala3-library-url"), "abe22d760d47702550c77c0fdd443f78ab2db582"),
            mapEntry(new ScalaHash("3.3.0", "tasty-core-url"), "43995ca7875870d6a54f656576f63dffe9433d6d"),
            mapEntry(new ScalaHash("3.3.1", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.3.1", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.3.1", "scala3-library-url"), "3b66116b7356758a850f5b9df710adf5a0210546"),
            mapEntry(new ScalaHash("3.3.1", "tasty-core-url"), "ab7f50592d0433b4d0503651f7f2e703697892dd"),
            mapEntry(new ScalaHash("3.3.2", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.3.2", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.3.2", "scala3-library-url"), "48aac435f7fb440637b4767a6d0f67d527df24b0"),
            mapEntry(new ScalaHash("3.3.2", "tasty-core-url"), "72520adeee725593c3bdd9d108143cf2030bedcd"),
            mapEntry(new ScalaHash("3.3.3", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.3.3", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.3.3", "scala3-library-url"), "8717a89f7030fde424b4ba44608fb2583b5ed159"),
            mapEntry(new ScalaHash("3.3.3", "tasty-core-url"), "eae28e0f18a38313bb17335ced6cc64c73aed145"),
            mapEntry(new ScalaHash("3.4.0", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.4.0", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.4.0", "scala3-library-url"), "b25d08c72dda53e45f74c139f43672e8cf9edb86"),
            mapEntry(new ScalaHash("3.4.0", "tasty-core-url"), "d1aec40f0fe0a4311a63639fdfc1c65942958e7b"),
            mapEntry(new ScalaHash("3.4.1", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.4.1", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.4.1", "scala3-library-url"), "d59f013ed89ace000307d2a773f0092eccdcf664"),
            mapEntry(new ScalaHash("3.4.1", "tasty-core-url"), "f0f3ae977d428cd33522b8b225a7e791df71a367"),
            mapEntry(new ScalaHash("3.4.2", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.4.2", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.4.2", "scala3-library-url"), "0c1ce7f324cfb933ca8ce291dbe585a9b3d94a71"),
            mapEntry(new ScalaHash("3.4.2", "tasty-core-url"), "91138cf7d4e352d285ca5e48cbdd4f77d928d9cf"),
            mapEntry(new ScalaHash("3.4.3", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.4.3", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.4.3", "scala3-library-url"), "c068e661c36078f33e88b682c9b2eb2b7e107ffe"),
            mapEntry(new ScalaHash("3.4.3", "tasty-core-url"), "473ddf5ede701fa152312eaa7af6ca7b0005e24f"),
            mapEntry(new ScalaHash("3.5.0", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.5.0", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.5.0", "scala3-library-url"), "81e3642750c9633276eba9f8f1609daefab0e49c"),
            mapEntry(new ScalaHash("3.5.0", "tasty-core-url"), "e66209381cb84fdfd57236f719d1abedf4918e92"),
            mapEntry(new ScalaHash("3.5.1", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.5.1", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.5.1", "scala3-library-url"), "fad444125865e38c6a3870229f4a5d3e05c38ea8"),
            mapEntry(new ScalaHash("3.5.1", "tasty-core-url"), "770409769909dc03103efa2d98e11797115b27bc"),
            mapEntry(new ScalaHash("3.5.2", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.5.2", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.5.2", "scala3-library-url"), "d88120b81e586e81cd835a283ddaf5d6c55b2d7f"),
            mapEntry(new ScalaHash("3.5.2", "tasty-core-url"), "d1415f8a1cbab81d6a2a11949541e028c51c98a1"),
            mapEntry(new ScalaHash("3.6.0", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.6.0", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.6.0", "scala3-library-url"), "4da35e99e5c69b97811690440a810204040bb704"),
            mapEntry(new ScalaHash("3.6.0", "tasty-core-url"), "64f8ffddc6514bf96839860a2c7adaf5821eeeeb"),
            mapEntry(new ScalaHash("3.6.1", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.6.1", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.6.1", "scala3-library-url"), "c2cacd2f2ee94ad67d65e101bb929ed2a6fbe36d"),
            mapEntry(new ScalaHash("3.6.1", "tasty-core-url"), "bdd29ec2d6afda526bddc87aee9b50b42ec6a977"),
            mapEntry(new ScalaHash("3.6.2", "scala-library-url"), "ed6f1d58968b16c5f9067d5cac032d952552de58"),
            mapEntry(new ScalaHash("3.6.2", "scala-reflect-url"), "355927b10366563a8f1b56c1f34ff376f2f7c8c5"),
            mapEntry(new ScalaHash("3.6.2", "scala3-library-url"), "0c3f9f3da15f8c0cdea22ced65f6cf3745454e9f"),
            mapEntry(new ScalaHash("3.6.2", "tasty-core-url"), "e9fd80f9a4b8c6e102bf173fda46e09e53abd1f2")
    );

    private ScalaHashes() {
    }

    public static String getSha1(String scalaVersion, String urlKey) {
        return SHA1_HASHES.get(new ScalaHash(scalaVersion, urlKey));
    }

    private static final class ScalaHash {
        private final String urlKey;
        private final String scalaVersion;

        private ScalaHash(String scalaVersion, String urlKey) {
            this.urlKey = urlKey;
            this.scalaVersion = scalaVersion;
        }

        @Override
        public boolean equals(Object o) {
            if (o == this) return true;
            if (!(o instanceof ScalaHash)) return false;

            ScalaHash that = (ScalaHash) o;
            return Objects.equals(this.urlKey, that.urlKey) && Objects.equals(this.scalaVersion, that.scalaVersion);
        }

        @Override
        public int hashCode() {
            return Objects.hash(urlKey, scalaVersion);
        }
    }


    public static void main(String[] args) throws IOException {
        for (ScalaVersion scalaVersion : ScalaVersion.values()) {
            Map<String, String> urls = scalaVersion.getUrls();
            for (Map.Entry<String, String> urlEntry : urls.entrySet()) {
                String urlKey = urlEntry.getKey();
                String fileUrl = urlEntry.getValue();

                String shaUrl = fileUrl.concat(".sha1");
                String sha1 = getHash(shaUrl);

                System.out.println(String.format("mapEntry(new ScalaHash(\"%s\", \"%s\"), \"%s\"),", scalaVersion.getVersion(), urlKey, sha1));
            }
        }
    }

    private static String getHash(String hashUrl) throws IOException {
        URL url = new URL(hashUrl);
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        InputStream inputStream = connection.getInputStream();
        return new String(Compat.readAllBytes(inputStream), StandardCharsets.UTF_8);
    }
}
