name: ScalaLoader
version: ${project.version}
main: xyz.janboerman.scalaloader.ScalaLoader
api-version: 1.13
load: STARTUP
author: Jannyboy11
website: https://github.com/Jannyboy11/ScalaPluginLoader
description:
  >
    API to create plugins in Scala more easily.
    Supports multiple versions of Scala concurrently.
    No need for a plugin.yml file.
    Can load plugins from Scala singleton 'object's.
    Loads only the necessary Scala classes at runtime.
    Provides a boilerplate-free event api.

commands:
  resetScalaUrl:
    usage: "/<command> all|[<scala version>]"
    description:
      >
        Resets the config URL of the built-in scala version.
        Useful if you overwrote some of the urls.
        If 'all' is provided as a scala version, this command resets the URLs of all the built-in scala versions.
    permission: scalaloader.resetscalaurls

permissions:
  scalaloaders.resetscalaurls:
    description: Allows users to reset the scala url configs.
    default: op
