name: JavaExample                                             #Ignored!
main: xyz.janboerman.scalaloader.example.java.ExamplePlugin   #Ignored!
version: 0.17.15-SNAPSHOT                                     #Ignored!
api-version: 1.13

commands:
  bar:
    description: "Command that verifies that the plugin.yml file stuff is actually loaded too"
    permission: javaexample.bar

permissions:
  javaexample.bar:
    description: Allows access to /bar
    default: true