name: ScalaLoader
version: ${project.version}
bootstrapper: xyz.janboerman.scalaloader.paper.ScalaLoaderBootstrap
main: xyz.janboerman.scalaloader.paper.ScalaLoader
api-version: 1.19
folia-supported: true
load: STARTUP
author: Jannyboy11
website: https://github.com/Jannyboy11/ScalaPluginLoader
description:
  >
    API to create plugins in Scala more easily.
    Supports multiple versions of Scala concurrently.
    No need for a plugin.yml file.
    Can load plugins from Scala singleton 'object's.
    Loads only the necessary Scala classes at runtime.
    Provides a boilerplate-free event api.
    Provides a boilerplate-free configuration-serialization api.

permissions:
  scalaloader.resetscalaurls:
    description: Allows users to reset the scala url configs.
    default: op
  scalaloader.dumpclass:
    description: Allows users to dump a class to the console/logs.
    default: op
  scalaloader.setdebug:
    description: Allows users to debug classloading.
    default: op
  scalaloader.listscalaplugins:
    description: Allows users to see the scala plugins by their scala scalaVersion.
    default: op
