name: Compile and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          # Use Eclipse Temurin's OpenJDK because Microsoft doesn't seem to want to build non-LTS releases.
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Install Paper
        run: |
          git config --global user.email "jannyboy11@example.com"
          git config --global user.name "Jannyboy11"
          git clone https://github.com/PaperMC/Paper
          cd Paper
          ./gradlew applyPatches
          ./gradlew createReobfBundlerJar
          ./gradlew build
          ./gradlew generateMetadataFileForMavenPublication
          ./gradlew generatePomFileForMavenPublication
          ./gradlew publishToMavenLocal
          cd ~/.m2/repository/io/papermc/paper/paper-server/1.20.2-R0.1-SNAPSHOT
          mvn install:install-file -DgroupId=io.papermc.paper -DartifactId=paper-server -Dversion=1.20.2-R0.1-SNAPSHOT -Dpackaging=jar -Dfile=paper-server-1.20.2-R0.1-SNAPSHOT-mojang-mapped.jar
          cd ~
      - name: Compile ScalaLoader
        run: mvn --batch-mode --update-snapshots verify -DfinalName=ScalaLoader
      - name: Create tagged release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ScalaLoader/target/ScalaLoader.jar
      - name: Deploy Javadoc
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.4.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-distribution: temurin
          java-version: 21
          custom-command: 'mvn package javadoc:aggregate -pl :ScalaPluginLoader,:ScalaLoader-Common,:ScalaLoader-Bukkit,:ScalaLoader-Paper'
          target-folder: javadoc
          project: maven