name: Compile and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'microsoft' # Use Microsoft build of OpenJDK because that is what vanilla Minecraft ships with nowadays
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
