name: Compile and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          # Use Eclipse Temurin's OpenJDK because Microsoft doesn't seem to want to build non-LTS releases.
          distribution: 'temurin'
          java-version: '20'
          cache: 'maven'
      - name: Install Paper
        run: |
          git clone https://github.com/PaperMC/Paper
          cd Paper
          ./gradlew applyPatches
          ./gradlew createReobfBundlerJar
          ./gradlew build
          ./gradlew generateMetadataFileForMavenPublication
          ./gradlew generatePomFileForMavenPublication
          ./gradlew publishToMavenLocal
          cd ~/.m2/repository/io/papermc/paper/paper-server/1.19.4-R0.1-SNAPSHOT
          mvn install:install-file -DgroupId=io.papermc.paper -DartifactId=paper-server -Dversion=1.19.4-R0.1-SNAPSHOT -Dpackaging=jar -Dfile=paper-server-1.19.4-R0.1-SNAPSHOT-mojang-mapped.jar
          cd ~
      - name: Compile ScalaLoader
        run: mvn --batch-mode --update-snapshots verify -DfinalName=ScalaLoader
      - name: Create tagged release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
           ScalaLoader/target/ScalaLoader.jar
