name: Compile and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          # Use Microsoft build of OpenJDK because that is what vanilla Minecraft ships with nowadays
          distribution: 'microsoft'
          java-version: '18'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
